---
title: "CCB Price Increase"
author: "Andrew Lin"
date: "2024-06-17"
output: html_document
---

```{r}
library(tidyverse)
library(DBI)
library(RPostgres)
library("readr") 

prod <- dbConnect(RPostgres::Postgres(),  
               host = 'crain-aspire-1.cdhessuxqdxg.us-east-1.redshift.amazonaws.com',
               port = 5439,
               user = 'aspireuser',
               password = 'Aspirecrainredshift1',
               dbname = 'prod',
               sslmode='require')


ccb_working_query<-dbGetQuery(prod,statement=read_file('ccb_working_query.sql'))
ccb_adv_data<-dbGetQuery(prod,statement=read_file('ccb_adv_query.sql'))
ccb_prod<-dbGetQuery(prod,"select * from prod.pelcro.subscription where businessunitcode='CCB'")

ccb_autorenew<-dbGetQuery(prod,statement=read_file('ccb_autorenew_investigatin.sql'))
```


```{r}
ccb_working_query%>%
  filter(donortype=="I")%>%
  filter(termlength=="Monthly")%>%
  filter(orderdate<=as.Date("03-14-2024",format="%m-%d-%Y")&expire_date>=as.Date("04-08-2024",format="%m-%d-%Y"))%>%
  filter(!str_detect(publicationcode,"Data|Plus|Health"))%>%
  filter(publicationcode!="Print")%>%
  group_by(isautorenew)


ccb_working_query%>%
  group_by(isautorenew)%>%
  summarise(n=n())
```



```{r}
reduced<-ccb_adv_data%>%
  filter(startissuedate>=as.Date("2016-01-01",format="%Y-%m-%d"))%>%
  group_by(shiptocustomernumber,ordernumber)%>%
  mutate(pub_level=ifelse(publicationcode=='CB1',1,
                          ifelse(publicationcode=='CB2',2,
                          ifelse(publicationcode=='CB3',3,4))),
         did_renew=ifelse(is.na(renewalordernumber),0,1),
         did_renew=max(did_renew))%>%
  mutate(max_pub=max(pub_level),
         termnumber=max(termnumber),
         rate=sum(rate),
         renewalrate=sum(renewalrate,na.rm=TRUE),
         )%>%
  filter(pub_level==max_pub)



migration_rows<-ccb_autorenew%>%
  group_by(subscriptionid)%>%
  arrange(start_date,.by_group=TRUE)%>%
  mutate(renewalordernumber=lead(ordernumber,order_by=subscriptionid),
         renewalrate=lead(rate,order_by=subscriptionid),
         renewalstartdate=lead(start_date,order_by=subscriptionid))%>%
  ungroup()%>%
  filter(!is.na(adv_sub_id))%>%
  group_by(subscriptionid,adv_sub_id,adv_order_number)%>%
  mutate(min_date=min(start_date))%>%
  filter(min_date==start_date)

migrated_rows<-reduced%>%
  left_join(migration_rows,by=c('subscriptionreference'='adv_sub_id','ordernumber'='adv_order_number'))%>%
  filter(!is.na(rate.y))%>%
  mutate(original_adv_cust_value=as.numeric(shiptocustomernumber),
         shiptocustomernumber=as.character(shiptocustomernumber),
         pubcode=publicationcode.y,
         termlength=termlength.x,
         rate=rate.x,
         orderdate=orderdate.x,
         brand='CCB',
         adv_subid=subscriptionreference,
         pelcro_subid=subscriptionid,
         isautorenew=isautorenew.x,
         donortype=donortype.y,
         renewalordernumber=as.character(renewalordernumber.y),
         renewalrate=renewalrate.y,
         renewalstartdate=renewalstartdate.y,
         ordernumber=as.character(ordernumber)
         )%>%
   select(shiptocustomernumber,original_adv_cust_value,ordernumber,orderdate,brand,pubcode,adv_subid,pelcro_subid,termnumber,isautorenew,startissuedate,expirationissuedate,rate,termlength,renewalordernumber,renewalrate,renewalstartdate,donortype)

adv_rows<-reduced%>%
  ungroup()%>%
  filter(!ordernumber%in%migrated_rows$ordernumber)%>%
  group_by(shiptocustomernumber)%>%
  arrange(termnumber,.by_group=TRUE)


advantage_rows<-adv_rows%>%
  mutate(original_adv_cust_value=as.double(shiptocustomernumber),
         shiptocustomernumber=as.character(shiptocustomernumber),
         pubcode=publicationcode,
         adv_subid=subscriptionreference,
         pelcro_subid=NA,
         brand=owningoffice)%>%
  select(shiptocustomernumber,original_adv_cust_value,ordernumber,orderdate,brand,pubcode,adv_subid,pelcro_subid,termnumber,isautorenew,startissuedate,expirationissuedate,rate,termlength,renewalordernumber,renewalrate,renewalstartdate,donortype)%>%
  filter(donortype=="I")
  
pelcro_rows<-ccb_autorenew%>%
  group_by(subscriptionid)%>%
  arrange(start_date,.by_group=TRUE)%>%
  mutate(renewalordernumber=lead(ordernumber,order_by=subscriptionid),
         renewalrate=lead(rate,order_by=subscriptionid),
         renewalstartdate=lead(start_date,order_by=subscriptionid))%>%
  ungroup()%>%
  filter(is.na(adv_sub_id)|!ordernumber%in%migration_rows)%>%
  group_by(subscriptionid,adv_sub_id,adv_order_number)

migration_termnumber<-migrated_rows%>%
  group_by(pelcro_subid,original_adv_cust_value)%>%
  summarise(m=max(termnumber))

p_rows<-pelcro_rows%>%
  group_by(subscriptionid)%>%
  arrange(start_date,.by_group=TRUE)%>%
  left_join(migration_termnumber,by=c("subscriptionid"="pelcro_subid"))%>%
  mutate(row_number=row_number())%>%
  mutate(termnumber=ifelse(is.na(m),0,m)+row_number)%>%
  mutate(shiptocustomernumber=as.character(customeraccountid),
         pelcro_subid=subscriptionid,
         renewalordernumber=as.character(renewalordernumber),
         pubcode=publicationcode,
         adv_subid=adv_sub_id,
         startissuedate=start_date,
         expirationissuedate=expire_date,
         ordernumber=as.character(ordernumber)
         )%>%
  ungroup()%>%
  select(shiptocustomernumber,original_adv_cust_value,ordernumber,orderdate,brand,pubcode,adv_subid,pelcro_subid,termnumber,isautorenew,startissuedate,expirationissuedate,rate,termlength,renewalordernumber,renewalrate,renewalstartdate,donortype)
```

```{r}
ccb_data<-advantage_rows%>%
  union(migrated_rows)%>%
  union(p_rows)%>%
  mutate(orderdate=as.character(orderdate),
         startissuedate=as.character(startissuedate),
         expirationissuedate=as.character(expirationissuedate),
         renewalrate=as.character(renewalrate),
         renewalstartdate=as.character(renewalstartdate),
         pelcro_subid=as.double(pelcro_subid))
```

```{r}
missing_adv_data_ccb<-ccb_adv_data%>%
  filter(donortype=="I")%>%
  filter(startissuedate>=as.Date("2016-01-01",format="%Y-%m-%d"))%>%
  filter(!subscriptionreference%in%ccb_data$subscriptionreference)%>%
  left_join(ccb_data,by=c("shiptocustomernumber"="original_adv_cust_value","ordernumber"="ordernumber"))%>%
  filter(is.na(shiptocustomernumber.y))%>%
  distinct()%>%
  mutate(original_adv_cust_value=as.double(shiptocustomernumber),
         shiptocustomernumber=as.character(shiptocustomernumber),
         pelcro_subid=NA,
         brand='CCB',
         pubcode=publicationcode,
         adv_subid=subscriptionreference,
         startissuedate=as.character(startissuedate.x),
         expirationissuedate=as.character(expirationissuedate.x),
         ordernumber=as.character(ordernumber),
         renewalordernumber=renewalordernumber.x,
         rate=rate.x,
         termlength=termlength.x,
         isautorenew=isautorenew.x,
         renewalstartdate=as.character(renewalstartdate.x),
         renewalrate=as.character(renewalrate.x),
         orderdate=as.character(orderdate.x),
         termnumber=termnumber.x,
         donortype=donortype.x
         )%>%
  select(shiptocustomernumber,original_adv_cust_value,ordernumber,orderdate,brand,pubcode,adv_subid,pelcro_subid,termnumber,isautorenew,startissuedate,expirationissuedate,rate,termlength,renewalordernumber,renewalrate,renewalstartdate,donortype)
  
```
````{r}
test%>%
  filter(brand=="MH")

ccb_prod%>%
  filter(!subscriptionid%in%ccb_autorenew$subscriptionid)%>%
  filter(ispaid==TRUE)
```

```{r}
ccb_adv_data%>%
  filter(donortype=="I")%>%
  filter(startissuedate>=as.Date("2016-01-01",format="%Y-%m-%d"))%>%
  filter(!ordernumber%in%ccb_data$ordernumber&!shiptocustomernumber%in%ccb_data$original_adv_cust_value)
  filter(!shiptocustomernumber%in5)
  left_join(ccb_data,by=c("shiptocustomernumber"="original_adv_cust_value","ordernumber"="ordernumber"))%>%
  filter(is.na(shiptocustomernumber.y))%>%
  distinct()
```
```{r}
reduced%>%
  ungroup()%>%
  filter(!ordernumber%in%migrated_rows$ordernumber)%>%
  group_by(shiptocustomernumber)%>%
  arrange(termnumber,.by_group=TRUE)%>%
   mutate(original_adv_cust_value=as.double(shiptocustomernumber),
         shiptocustomernumber=as.character(shiptocustomernumber),
         pubcode=publicationcode,
         adv_subid=subscriptionreference,
         pelcro_subid=NA,
         brand=owningoffice)%>%
  select(shiptocustomernumber,original_adv_cust_value,ordernumber,orderdate,brand,pubcode,adv_subid,pelcro_subid,termnumber,isautorenew,startissuedate,expirationissuedate,rate,termlength,renewalordernumber,renewalrate,renewalstartdate,donortype)%>%
  filter(ordernumber=="C9988728")
```
```{r}
full_list_excluding<-test%>%
  union(ccb_data)%>%
  union(missing_adv_data_ccb)%>%
  union(adv_data_anc)

write.csv(full_list_excluding_ac,"full_list_excluding_ac.csv")
write.csv(full_list_excluding,"full_list_mapped_2.csv")
write.csv(full_list_excluding,"full_list_mapped_3.csv")

ccb_data%>%
  union(missing_adv_data_ccb)
```


```{r}
new_ccb_users<-ccb_working_query%>%
  filter(donortype=="I")%>%
  mutate(adv_sub_id=as.numeric(adv_sub_id))%>%
  filter(is.na(adv_sub_id))

migration_rows<-ccb_working_query%>%
  filter(donortype=="I")%>%
  mutate(adv_sub_id=as.numeric(adv_sub_id))%>%
  filter(!is.na(adv_sub_id))%>%
  group_by(subscriptionid)%>%
  mutate(min_start_date=min(start_date))%>%
  filter(min_start_date==start_date)

pelcro_layers<-ccb_working_query%>%
  filter(donortype=="I")%>%
  mutate(adv_sub_id=as.numeric(adv_sub_id))%>%
  filter(!is.na(adv_sub_id))%>%
  group_by(subscriptionid)%>%
  mutate(min_start_date=min(start_date))%>%
  filter(min_start_date!=start_date)

migration_rows%>%
  group_by(publicationcode)%>%
  filter(str_detect(publicationcode,"Print"))
```


```{r}
ccb_adv_data%>%
  mutate(is_migrated=ifelse(subscriptionreference%in%migration_rows$adv_sub_id,1,0))%>%
  group_by(shiptocustomernumber,ordernumber)%>%
  mutate(termnumber=max(termnumber),
         rate=sum(rate))%>%
  mutate(max_is_migrated=max(is_migrated))%>%
  filter(is_migrated==max_is_migrated)
  mutate(sub)
```

```{r}
ccb_adv_data%>%
  filter(subscriptionreference==19759634)
  filter(shiptocustomernumber==39749420&ordernumber=='D4415612')
```



```{r}
list_of_migrated_adv_accounts<-ccb_working_query%>%
  filter(donortype=="I")%>%
  group_by(subscriptionid)%>%
  arrange(start_date,.by_group=TRUE)%>%
  filter(!is.na(adv_sub_id))%>%
  mutate(adv_sub_id=as.numeric(adv_sub_id))
  filter(orderdate<=as.Date("04-27-2024",format="%m-%d-%Y")&expire_date>=as.Date("04-27-2024",format="%m-%d-%Y"))
```

```{r}
last_term<-ccb_adv_data%>%
  filter(subscriptionreference%in%list_of_migrated_adv_accounts$adv_sub_id&ordernumber%in%list_of_migrated_adv_accounts$adv_order_number)%>%
  group_by(subscriptionreference,ordernumber)%>%
  summarise(m=max(termnumber),
            f=max(expirationissuedate))
```

```{r}
ccb_list<-ccb_working_query%>%
  filter(donortype=="I")%>%
  group_by(subscriptionid)%>%
  arrange(start_date,.by_group=TRUE)%>%
  mutate(adv_sub_id=as.numeric(adv_sub_id))%>%
  mutate(ordernumber=as.character(ordernumber))%>%
  left_join(last_term,by=c("adv_sub_id"="subscriptionreference","adv_order_number"="ordernumber"))%>%
  separate(start_date,into=c("start_date","start_time"),sep=" ")%>%
  separate(orderdate,into=c("order_date","order_time"),sep=" ")%>%
  separate(expire_date,into=c("expire_date","expire_time"),sep=" ")%>%
  mutate(order_date=ifelse(is.na(order_date),start_date,order_date))%>%
  mutate(order_date=as.Date(order_date,format="%Y-%m-%d"))%>%
  mutate(start_date=as.Date(start_date,format="%Y-%m-%d"))%>%
  mutate(expire_date=as.Date(expire_date,format="%Y-%m-%d"))%>%
  mutate(termnumber=row_number()-1)%>%
  mutate(termnumber=ifelse(f==start_date,m,termnumber+m))%>%
  select(subscriptionid,ordernumber,customeraccountid,termnumber,termlength,isautorenew,totalprice,publicationcode,donortype,start_date,expire_date,rate,order_date)%>%
  arrange(start_date,.by_group=TRUE)%>%
  mutate(ordernumber=ifelse(is.na(ordernumber),paste(subscriptionid,termnumber),ordernumber))%>%
  mutate(termnumber=ifelse(is.na(termnumber),row_number(),termnumber))%>%
  mutate(renewaltermnumber=lead(termnumber,order_by=c(start_date)),
         renewalrate=lead(rate,order_by=c(start_date)),
         renewalpublicationcode=lead(publicationcode,order_by=c(start_date)),
         renewalorderdate=lead(order_date,order_by=c(start_date)),
         renewalstartdate=lead(start_date,order_by=c(start_date)),
         renewaltermlength=lead(termlength,order_by=c(start_date)),
         renewalordernumber=lead(ordernumber,order_by=start_date))
```


```{r}
full_list_excluding%>%
  filter(brand=="CCB")


ccb_prod%>%
  filter(!subscriptionid%in%full_list_excluding$pelcro_subid)%>%
  filter(ispaid==TRUE&issourced==TRUE)
```


Annual Customers

```{r}
full_list_excluding%>%
  filter(brand=="CCB")%>%
  filter(termlength=="Annual")%>%
  filter(orderdate<=as.Date("03-14-2024",format="%m-%d-%Y")&expirationissuedate>=as.Date("04-27-2024",format="%m-%d-%Y"))%>%
  filter(!str_detect(pubcode,"Data|Plus|Health"))%>%
  filter(pubcode!="Print")%>%
  mutate(termnumber=as.numeric(termnumber))%>%
  group_by(pubcode,isautorenew)%>%
  summarise(n_distinct_contracts=n_distinct(paste(shiptocustomernumber,ordernumber,pelcro_subid)),
            n_distinct_renewals_increase=n_distinct(ifelse((!is.na(renewalordernumber)&renewalrate>=199&pubcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&pubcode=="Premium"),paste(shiptocustomernumber,ordernumber,pelcro_subid),NA),na.rm=TRUE),
            n_distinct_renewals_no_increase=n_distinct(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,paste(shiptocustomernumber,ordernumber,pelcro_subid),NA),na.rm=TRUE),
            n_distinct_undetermined=n_distinct(ifelse(is.na(renewalordernumber)&expirationissuedate>=today(),paste(shiptocustomernumber,ordernumber,pelcro_subid),NA),na.rm=TRUE),
            n_distinct_churned=n_distinct(ifelse(is.na(renewalordernumber)&expirationissuedate<today(),paste(shiptocustomernumber,ordernumber,pelcro_subid),NA),na.rm=TRUE),
            mean_rate_renewal_price_increase=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=199&pubcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&pubcode=="Premium"),rate,NA),na.rm=TRUE),
            mean_rate_churn_price_increase=mean(ifelse(is.na(renewalordernumber)&expirationissuedate<today(),rate,NA),na.rm=TRUE),
            mean_termnumber_pi_renewal=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=199&pubcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&pubcode=="Premium"),termnumber,NA),na.rm=TRUE),
            mean_termnumber_churn=mean(ifelse(is.na(renewalordernumber)&expirationissuedate<today(),termnumber,NA),na.rm=TRUE),
            renewal_price_increase_revenue=sum(ifelse((!is.na(renewalordernumber)&renewalrate>=199&pubcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&pubcode=="Premium"),as.numeric(renewalrate),NA),na.rm=TRUE),
            renewal_no_price_increase_revenue=sum(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,as.numeric(renewalrate),NA),na.rm=TRUE),
            churn_loss=-1*sum(ifelse(is.na(renewalordernumber)&expirationissuedate<today()&pubcode=="Basic Digital",199,
                                     ifelse(is.na(renewalordernumber)&expirationissuedate<today()&pubcode=="Premium",225,NA)),na.rm=TRUE),
            total_renewal_revenue_post_price_increase=renewal_price_increase_revenue+renewal_no_price_increase_revenue+churn_loss)
  
```


```{r}
ccb_list%>%
  filter(termlength=="Monthly")%>%
  filter(order_date<=as.Date("03-14-2024",format="%m-%d-%Y")&expire_date>=as.Date("04-08-2024",format="%m-%d-%Y"))%>%
  filter(!str_detect(publicationcode,"Data|Plus|Health"))%>%
  filter(publicationcode!="Print")%>%
  mutate(termnumber=as.numeric(termnumber))%>%
  group_by(subscriptionid,ordernumber,customeraccountid)%>%
  mutate(min_date=min(order_date))%>%
  filter(order_date==min_date)%>%
  group_by(publicationcode,isautorenew)%>%
  summarise(n_distinct_contracts=n_distinct(paste(customeraccountid,ordernumber,subscriptionid)),
            n_distinct_renewals_increase=n_distinct(ifelse((!is.na(renewalordernumber)&renewalrate>=18&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=20&publicationcode=="Premium"),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_renewals_no_increase=n_distinct(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_undetermined=n_distinct(ifelse(is.na(renewalorderdate)&expire_date>=today(),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_churned=n_distinct(ifelse(is.na(renewalorderdate)&expire_date<today(),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            mean_rate_renewal_price_increase=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=18&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=20&publicationcode=="Premium"),rate,NA),na.rm=TRUE),
            mean_rate_churn_price_increase=mean(ifelse(is.na(renewalordernumber)&expire_date<today(),rate,NA),na.rm=TRUE),
            mean_termnumber_pi_renewal=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=18&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=20&publicationcode=="Premium"),termnumber,NA),na.rm=TRUE),
            mean_termnumber_churn=mean(ifelse(is.na(renewalordernumber)&expire_date<today(),termnumber,NA),na.rm=TRUE),
            renewal_price_increase_revenue=sum(ifelse((!is.na(renewalordernumber)&renewalrate>=18&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=20&publicationcode=="Premium"),as.numeric(renewalrate),NA),na.rm=TRUE),
            renewal_no_price_increase_revenue=sum(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,as.numeric(renewalrate),NA),na.rm=TRUE),
            churn_loss=-1*sum(ifelse(is.na(renewalordernumber)&expire_date<today()&publicationcode=="Basic Digital",18,
                                     ifelse(is.na(renewalordernumber)&expire_date<today()&publicationcode=="Premium",20,NA)),na.rm=TRUE),
            total_renewal_revenue_post_price_increase=renewal_price_increase_revenue+renewal_no_price_increase_revenue+churn_loss)
  
```
Annual New Orders


```{r}
ccb_list%>%
  filter(termlength=="Annual")%>%
  filter(order_date>=as.Date("03-14-2024",format="%m-%d-%Y")&termnumber==1)%>%
  filter(!str_detect(publicationcode,"Data|Plus|Health"))%>%
  filter(publicationcode!="Print")%>%
  mutate(termnumber=as.numeric(termnumber))%>%
  group_by(publicationcode,isautorenew)%>%
  summarise(n_distinct_contracts=n_distinct(paste(customeraccountid,ordernumber,subscriptionid)),
            n_distinct_renewals_increase=n_distinct(ifelse((!is.na(renewalordernumber)&renewalrate>=199&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&publicationcode=="Premium"),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_renewals_no_increase=n_distinct(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_undetermined=n_distinct(ifelse(is.na(renewalorderdate)&expire_date>=today(),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            n_distinct_churned=n_distinct(ifelse(is.na(renewalorderdate)&expire_date<today(),paste(customeraccountid,ordernumber,subscriptionid),NA),na.rm=TRUE),
            mean_rate_renewal_price_increase=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=199&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&publicationcode=="Premium"),rate,NA),na.rm=TRUE),
            mean_rate_churn_price_increase=mean(ifelse(is.na(renewalordernumber)&expire_date<today(),rate,NA),na.rm=TRUE),
            mean_termnumber_pi_renewal=mean(ifelse((!is.na(renewalordernumber)&renewalrate>=199&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&publicationcode=="Premium"),termnumber,NA),na.rm=TRUE),
            mean_termnumber_churn=mean(ifelse(is.na(renewalordernumber)&expire_date<today(),termnumber,NA),na.rm=TRUE),
            renewal_price_increase_revenue=sum(ifelse((!is.na(renewalordernumber)&renewalrate>=199&publicationcode=="Basic Digital")|(!is.na(renewalordernumber)&renewalrate>=225&publicationcode=="Premium"),as.numeric(renewalrate),NA),na.rm=TRUE),
            renewal_no_price_increase_revenue=sum(ifelse(!is.na(renewalordernumber)&renewalrate<=rate,as.numeric(renewalrate),NA),na.rm=TRUE),
            churn_loss=-1*sum(ifelse(is.na(renewalordernumber)&expire_date<today()&publicationcode=="Basic Digital",199,
                                     ifelse(is.na(renewalordernumber)&expire_date<today()&publicationcode=="Premium",225,NA)),na.rm=TRUE),
            total_renewal_revenue_post_price_increase=renewal_price_increase_revenue+renewal_no_price_increase_revenue+churn_loss)
```

